### ISSUE TITLE
Cartouche

### ISSUE THREAD

**Issue by caillou15** [julmg/ultimate-road-signs-mod#1]
J'ai remarqué qu'il manque le cartouche blanc pour les voies communales.
À part ça, je trouve que le mod est un bon début, dommage que le développement ne semble pas actif, il n'existait pas de mod de panneaux français. Je pourrais aider au développement.
Ça pourrait être super aussi de faire des panneaux de direction à plusieurs lignes de texte.

**Comment by julmg** [comment]
Merci, je viens d'ajouter le cartouche blanc.
Je me replongerai dans l'opengl à l'occasion pour ajouter des panneaux à 2 lignes.
