### ISSUE TITLE
Empiler les cartouches

### ISSUE THREAD

**Issue by caillou15** [julmg/ultimate-road-signs-mod#3]
Je viens de tester le mod, il est trop bien ! C'est réaliste.
J'ai une autre proposition de fonctionnalité : la possibilité d'empiler les cartouches. Ça sera utile si on veut mettre les cartouches de route européenne par exemple

**Comment by julmg** [comment]
Merci !! J'ai ajouté un cartouche à 2 couleurs vert+rouge pour route européenne+nationale/autoroute. Ca sera fait dans la prochaine version à venir d'ici qq jours.
